import pygame

# movements
MOVE_RIGHT   = pygame.K_RIGHT
MOVE_LEFT    = pygame.K_LEFT
MOVE_DOWN    = pygame.K_DOWN
ROTATE_LEFT  = pygame.K_z
ROTATE_RIGHT = pygame.K_x
HARD_DROP    = pygame.K_SPACE

# GAME SIZE
COLUMNS = 10
ROWS = 20
CELL_SIZE = 30 # playfield/game
APPNAME_SIZE = 24
GAME_WIDTH, GAME_HEIGHT = COLUMNS*CELL_SIZE, ROWS*CELL_SIZE

# RIGHTBAR
RIGHTBAR_WIDTH = 200
PREVIEW_HEIGHT_FRACTION = 0.65
SCORE_HEIGHT_FRACTION = 1-PREVIEW_HEIGHT_FRACTION

#LEFTBAR
LEFTBAR_WIDTH = 180
CONTROLS_HEIGHT = 110
SCORING_HEIGHT= 130
CONTROLS_TEXT = ["CONTROLS", "← →  Move", "↓  Soft Drop", "x z  Rotate", "SPACE  Hard Drop"]
SCORING_TEXT = ["SCORING", "1 Line: 40", "2 Lines: 100", "3 Line: 300" , "4 Line: 1200"]

# WINDOW
PADDING = 10 #BORDER
WINDOW_WIDTH = GAME_WIDTH + RIGHTBAR_WIDTH +LEFTBAR_WIDTH+ PADDING*4
WINDOW_HEIGHT = GAME_HEIGHT + PADDING*3 + APPNAME_SIZE

# COLORS
YELLOW = '#f1e60d'
RED = '#e51b20'
BLUE = '#204b9b'
GREEN = '#65b32e'
PURPLE = '#7b217f'
CYAN = '#6cc6d9'
ORANGE = '#f07e13'
GRAY = '#1C1C1C'
DARK_GRAY = '#A9A9A9'
BLACK = '#000000'
LINE_COLOR = '#FFFFFF'

FRAMEPERSEC = 60

# Game mode settings
GAME_MODE = "player"
AI_DIFFICULTY = "medium"